#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 13 13:34:52 EET 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim seq_core_pipeline_testbench_behav -key {Behavioral:sim_1:Functional:seq_core_pipeline_testbench} -tclbatch seq_core_pipeline_testbench.tcl -view /home/tudor/_code/risc-proc/vivado/seq_core_pipeline_testbench_behav.wcfg -log simulate.log"
xsim seq_core_pipeline_testbench_behav -key {Behavioral:sim_1:Functional:seq_core_pipeline_testbench} -tclbatch seq_core_pipeline_testbench.tcl -view /home/tudor/_code/risc-proc/vivado/seq_core_pipeline_testbench_behav.wcfg -log simulate.log

